#!/usr/bin/env python3
# -*- coding: utf-8 -*

##
#  makeNovel – Starting Script
# =============================
##

import sys
import mknov

if __name__ == "__main__":
  mknov.main(sys.argv[1:])

# End Main File
